name: Prova_PRW1_2025-1

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
    container_name: services
    depends_on:
      - backend
    networks:
      rede_interna:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3000:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      rede_interna:
    depends_on:
      - database

  database:
    image: mariadb:11
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
    ports:
      - "3307:3306"
    networks:
      rede_interna:
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  rede_interna: